// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/factory/annotation

package config

import (
	"github.com/expgo/factory"
)

var (
	__context = factory.Singleton[context]().Get()
)
