// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/factory/annotation

package serve

import (
	"github.com/expgo/factory"
)

var (
	__FileWatchServe = factory.Getter[FileWatchServe](factory.Singleton[FileWatchServe]())
)
